services:
  banktransfer:
    build:
      context: ./src
      dockerfile: banktransfer/Dockerfile
    environment:
      - KAFKA_CONNECT=kafka:9092
  myaktion:
    build:
      context: ./src
      dockerfile: myaktion/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECT=mariadb:3306
      - BANKTRANSFER_CONNECT=banktransfer:9111
      - LOG_LEVEL=info # change to trace for debugging
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myaktion
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1